api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : src
env_make : ~
env_prep : get-composer
env_post : ci-coveralls,ci-codacy
php_conf : timezone
php_exts : igbinary,memcached
app_prep : dep-composer
app_post : ~
app_path : bin/teavee-scribble-down
pkg_name : teavee-scribble-down-bundle
pkg_desc : "a Markdown-based rendering engine with additional features."
pkg_bndl : true
